const FETCH_JOBS = 'FECTH_JOBS'
const APPLY_JOBS = 'APPLY_JOBS'
const FETCH_USER = 'FETCH_USER'
const FETCH_LOST = 'FETCH_LOST'
const CHECK_LOGIN = 'CHECK_LOGIN'
const FILTER_TIME = 'FILTER_TIME'
const FILTER_PERSON = 'FILTER_PERSON'
const FILTER_PRICE = 'FILTER_PRICE'
const FETCH_DRIVER = 'FETCH_DRIVER'
const FETCH_MORE = 'FETCH_MORE'
const MERCHANT_LOGIN = 'MERCHANT_LOGIN'
const FETCH_MERCHANT_JOBS = 'FETCH_MERCHANT_JOBS'
const MAKESIGNINCODE = 'MAKESIGNINCODE'
const MAKESIGNOUTCODE = 'MAKESIGNOUTCODE'
const FETCH_MY_JOBS = 'FETCH_MY_JOBS'
const JOB_SIGN_STATUS = 'JOB_SIGN_STATUS'
const ENROLL = 'ENROLL'
const FETCH_TODAY_JOBS = 'FETCH_TODAY_JOBS'
const FETCH_SLIDERS = 'FETCH_SLIDERS'
const RESET_LIST = 'RESET_LIST'
const FIX_PHONE = 'FIX_PHONE'

export {
  FETCH_JOBS,
  FETCH_USER,
  APPLY_JOBS,
  FETCH_LOST,
  CHECK_LOGIN,
  FILTER_TIME,
  FILTER_PERSON,
  FILTER_PRICE,
  FETCH_DRIVER,
  FETCH_MORE,
  MERCHANT_LOGIN,
  FETCH_MERCHANT_JOBS,
  MAKESIGNINCODE,
  MAKESIGNOUTCODE,
  FETCH_MY_JOBS,
  JOB_SIGN_STATUS,
  ENROLL,
  FETCH_TODAY_JOBS,
  FETCH_SLIDERS,
  RESET_LIST,
  FIX_PHONE
}
